import os
import configparser
from core.os_utils import get_config_path

# Default server config values used by the manager
DEFAULT_CONFIG = {
    'server_name': 'My The Isle Server',
    'server_password': '',
    'admin_password': 'changeme123',
    'max_players': 100,
    'map': 'Gateway',
    'game_port': 7777,
    'query_port': 27015,
    'rcon_port': 27020,
    'rcon_password': '',
    'day_length': 60,
    'night_length': 30,
    'allow_dinosaur_selection': True,
    'growth_multiplier': 1.0,
    'food_multiplier': 1.0,
    'water_multiplier': 1.0,
    'stamina_multiplier': 1.0,
    'bleed_multiplier': 1.0,
    'website_url': '',
    'discord_url': '',
}

MANAGER_CONFIG_FILE = 'manager_config.ini'


def save_manager_config(base_path: str, config: dict) -> bool:
    """Save manager settings to a simple INI file"""
    cfg = configparser.ConfigParser()
    cfg['server'] = {str(k): str(v) for k, v in config.items()}
    path = os.path.join(base_path, MANAGER_CONFIG_FILE)
    try:
        os.makedirs(base_path, exist_ok=True)
        with open(path, 'w') as f:
            cfg.write(f)
        return True
    except Exception as e:
        print(f"[Config] Error saving: {e}")
        return False


def load_manager_config(base_path: str) -> dict:
    """Load manager settings; returns defaults if not found"""
    path = os.path.join(base_path, MANAGER_CONFIG_FILE)
    config = dict(DEFAULT_CONFIG)
    if not os.path.exists(path):
        return config
    try:
        cfg = configparser.ConfigParser()
        cfg.read(path)
        if 'server' in cfg:
            section = cfg['server']
            for key in DEFAULT_CONFIG:
                if key in section:
                    val = section[key]
                    default = DEFAULT_CONFIG[key]
                    if isinstance(default, bool):
                        config[key] = val.lower() in ('true', '1', 'yes')
                    elif isinstance(default, int):
                        config[key] = int(val)
                    elif isinstance(default, float):
                        config[key] = float(val)
                    else:
                        config[key] = val
    except Exception as e:
        print(f"[Config] Error loading: {e}")
    return config


def write_game_ini(install_path: str, config: dict, os_type: str = None) -> bool:
    """Write Game.ini with current config values"""
    cfg_path = get_config_path(install_path, os_type)
    os.makedirs(cfg_path, exist_ok=True)
    game_ini = os.path.join(cfg_path, 'Game.ini')

    content = f"""; The Isle Evrima - Game.ini
; Generated by The Isle Server Manager

[/Script/TheIsle.TIGameSession]
MaxPlayers={config.get('max_players', 100)}

[/Script/TheIsle.TIGameMode]
DayLength={config.get('day_length', 60)}
NightLength={config.get('night_length', 30)}
AllowDinosaurSelection={str(config.get('allow_dinosaur_selection', True)).lower()}

[/Script/TheIsle.TIGameState]
ServerName={config.get('server_name', 'The Isle Server')}
WebsiteURL={config.get('website_url', '')}
DiscordURL={config.get('discord_url', '')}

[/Script/TheIsle.TIPlayerController]
GrowthMultiplier={config.get('growth_multiplier', 1.0)}
FoodMultiplier={config.get('food_multiplier', 1.0)}
WaterMultiplier={config.get('water_multiplier', 1.0)}
StaminaMultiplier={config.get('stamina_multiplier', 1.0)}
BleedMultiplier={config.get('bleed_multiplier', 1.0)}
"""
    try:
        with open(game_ini, 'w') as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"[Config] Error writing Game.ini: {e}")
        return False


def write_game_user_settings(install_path: str, config: dict, os_type: str = None) -> bool:
    """Write GameUserSettings.ini"""
    cfg_path = get_config_path(install_path, os_type)
    os.makedirs(cfg_path, exist_ok=True)
    settings_ini = os.path.join(cfg_path, 'GameUserSettings.ini')

    password_line = f'ServerPassword={config.get("server_password", "")}' if config.get('server_password') else ''
    admin_line = f'AdminPassword={config.get("admin_password", "")}'

    content = f"""; The Isle Evrima - GameUserSettings.ini
; Generated by The Isle Server Manager

[ServerSettings]
{password_line}
{admin_line}
GamePort={config.get('game_port', 7777)}
QueryPort={config.get('query_port', 27015)}
RCONPort={config.get('rcon_port', 27020)}
RCONPassword={config.get('rcon_password', '')}
"""
    try:
        with open(settings_ini, 'w') as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"[Config] Error writing GameUserSettings.ini: {e}")
        return False




def write_engine_ini(install_path: str, os_type: str = None) -> bool:
    """Write Engine.ini with required EOS credentials."""
    from core.os_utils import get_config_path
    cfg_path = get_config_path(install_path, os_type)
    os.makedirs(cfg_path, exist_ok=True)
    engine_ini = os.path.join(cfg_path, 'Engine.ini')
    content = """; The Isle Evrima - Engine.ini
; Generated by The Isle Server Manager
; EOS credentials required for server startup

[OnlineSubsystemEOS]
bEnabled=true

[EpicOnlineServices]
DedicatedServerClientId=xyza7891gk5PRo3J7G9puCJGFJjmEguW
DedicatedServerClientSecret=pKWl6t5i9NJK8gTpVlAxzENZ65P8hYzodV8Dqe5Rlc8

[/Script/OnlineSubsystemEOS.NetDriverEOS]
bIsDefaultNetDriver=true
"""
    try:
        with open(engine_ini, 'w') as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"[Config] Error writing Engine.ini: {e}")
        return False

def write_all_configs(install_path: str, config: dict, os_type: str = None) -> bool:
    ok1 = write_game_ini(install_path, config, os_type)
    ok2 = write_game_user_settings(install_path, config, os_type)
    ok3 = write_engine_ini(install_path, os_type)
    return ok1 and ok2 and ok3
